/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AnnouncementsBell: typeof import('./src/components/announcements/AnnouncementsBell.vue')['default']
    AppHeader: typeof import('./src/components/shell/AppHeader.vue')['default']
    AppMobileNav: typeof import('./src/components/shell/AppMobileNav.vue')['default']
    AppShell: typeof import('./src/components/shell/AppShell.vue')['default']
    AppSidebar: typeof import('./src/components/shell/AppSidebar.vue')['default']
    DataTable: typeof import('./src/components/common/DataTable.vue')['default']
    EmptyState: typeof import('./src/components/common/EmptyState.vue')['default']
    GradeBadge: typeof import('./src/components/common/GradeBadge.vue')['default']
    MarkdownText: typeof import('./src/components/common/MarkdownText.vue')['default']
    PageSkeleton: typeof import('./src/components/common/PageSkeleton.vue')['default']
    PublishFields: typeof import('./src/components/common/PublishFields.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    ScratchFrame: typeof import('./src/components/scratch/ScratchFrame.vue')['default']
  }
}
