/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AlertBanner: typeof import('./src/components/announcements/AlertBanner.vue')['default']
    AnnouncementCard: typeof import('./src/components/announcements/AnnouncementCard.vue')['default']
    AnnouncementFormDialog: typeof import('./src/components/faculty/AnnouncementFormDialog.vue')['default']
    AnnouncementPreview: typeof import('./src/components/faculty/AnnouncementPreview.vue')['default']
    AnnouncementsBell: typeof import('./src/components/announcements/AnnouncementsBell.vue')['default']
    AppHeader: typeof import('./src/components/shell/AppHeader.vue')['default']
    AppMobileNav: typeof import('./src/components/shell/AppMobileNav.vue')['default']
    AppShell: typeof import('./src/components/shell/AppShell.vue')['default']
    AppSidebar: typeof import('./src/components/shell/AppSidebar.vue')['default']
    AssignmentFormDialog: typeof import('./src/components/faculty/AssignmentFormDialog.vue')['default']
    AssignmentPreview: typeof import('./src/components/faculty/AssignmentPreview.vue')['default']
    AssignmentTable: typeof import('./src/components/assignments/AssignmentTable.vue')['default']
    AssignSubmissionDialog: typeof import('./src/components/faculty/AssignSubmissionDialog.vue')['default']
    BulkAssignBar: typeof import('./src/components/faculty/BulkAssignBar.vue')['default']
    DataTable: typeof import('./src/components/common/DataTable.vue')['default']
    DeleteAnnouncementDialog: typeof import('./src/components/faculty/DeleteAnnouncementDialog.vue')['default']
    DeleteAssignmentDialog: typeof import('./src/components/faculty/DeleteAssignmentDialog.vue')['default']
    EmptyState: typeof import('./src/components/common/EmptyState.vue')['default']
    FacultySelect: typeof import('./src/components/faculty/FacultySelect.vue')['default']
    GradeBadge: typeof import('./src/components/common/GradeBadge.vue')['default']
    GradeDialog: typeof import('./src/components/assignments/GradeDialog.vue')['default']
    GradeForm: typeof import('./src/components/grading/GradeForm.vue')['default']
    GradeSubmissionDialog: typeof import('./src/components/faculty/GradeSubmissionDialog.vue')['default']
    MarkdownText: typeof import('./src/components/common/MarkdownText.vue')['default']
    PageSkeleton: typeof import('./src/components/common/PageSkeleton.vue')['default']
    PreviewAnnouncementDialog: typeof import('./src/components/faculty/PreviewAnnouncementDialog.vue')['default']
    ProjectCard: typeof import('./src/components/projects/ProjectCard.vue')['default']
    PublishAnnouncementDialog: typeof import('./src/components/faculty/PublishAnnouncementDialog.vue')['default']
    PublishAssignmentDialog: typeof import('./src/components/faculty/PublishAssignmentDialog.vue')['default']
    PublishFields: typeof import('./src/components/common/PublishFields.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    ScratchFrame: typeof import('./src/components/scratch/ScratchFrame.vue')['default']
    SettingsDialog: typeof import('./src/components/settings/SettingsDialog.vue')['default']
    SubmissionPlayer: typeof import('./src/components/grading/SubmissionPlayer.vue')['default']
    SubmissionPreviewDialog: typeof import('./src/components/assignments/SubmissionPreviewDialog.vue')['default']
    SubmitAssignmentDialog: typeof import('./src/components/assignments/SubmitAssignmentDialog.vue')['default']
    SubmitProjectDialog: typeof import('./src/components/projects/SubmitProjectDialog.vue')['default']
  }
}
